"""health_bot

Revision ID: c0b352f1f51f
Revises:
Create Date: 2023-06-02 21:42:48.872542

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c0b352f1f51f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_info',
                    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
                    sa.Column('only_headaches', sa.Boolean(), nullable=True),
                    sa.Column('only_blood', sa.Boolean(), nullable=True),
                    sa.Column('both_mode', sa.Boolean(), nullable=True),
                    sa.Column('push_mode_1', sa.Boolean(), nullable=True),
                    sa.Column('push_mode_2', sa.Boolean(), nullable=True),
                    sa.Column('one_time_push', sa.Time(), nullable=True),
                    sa.Column('first_time_push', sa.Time(), nullable=True),
                    sa.Column('second_time_push', sa.Time(), nullable=True),
                    sa.PrimaryKeyConstraint('telegram_id'),
                    sa.UniqueConstraint('telegram_id'))
    op.create_table('health_diary',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
                    sa.Column('date', sa.Date(),
                              server_default=sa.text('CURRENT_DATE'),
                              nullable=True),
                    sa.Column('headaches', sa.String(length=20),
                              nullable=True),
                    sa.Column('blood_pressure',
                              sa.String(length=15), nullable=True),
                    sa.Column('drugs', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['telegram_id'],
                                            ['users_info.telegram_id'], ),
                    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_diary')
    op.drop_table('users_info')
    # ### end Alembic commands ###
